token: "" #Токен 
rcon_host: "" #Айпишник сервера
rcon_port:  #Порт для ркона
rcon_password: "" #Пароль для ркона
alert_channel:  #Канал, где будет писаться кто и кого добавил/удалил из вайтлиста
role_id:  #Роль, которая выдаётся игроку при /whitelist add // нажатии кнопки
whitelist_role_id:  #Айди роли, которая даёт право на добавление в вайтлист
bot_admin:  #Айди роли, которая может сетапить вайтлист, создавать эмбеды и т.д
